---
name: look
description: look after action
inputs:
  son:
    description: who is the son
    required: true
    default: Nathan
outputs:
  father:
    description: father of the son
    value: ${{steps.find-father.outputs.found}}

runs:
  using: composite
  steps:
  - name: Show Son
    run: echo ${{inputs.son}}
    shell: bash
  - name: Find father
    id: find-father
    shell: bash
    run: echo "found=EthanLi" >> $GITHUB_OUTPUT
