on: [pull_request_target, issues]
jobs:
  greeting:
    name: Greeting job
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      run: echo How are you
name: May Flowers Greeting Workflow